CREATE TABLE DEPARTMENT
DEPT_NUMBER CHAR(6) PRIMARY KEY, 
DEPT_NAME VARCHAR (20) NOT NULL UNIQUE,
LOCATION VARCHAR (20) );

ALTER TABLE DEPARTMENT
MODIFY DEPT_NAME VARCHAR (100)

ALTER TABLE DEPARTMENT
ADD MANAGER VARCHAR(45)

ALTER TABLE DEPARTMENT
DROP COLUMN MANAGER

CREATE TABLE EMPLOYEES
(
EMP_NUMBER NUMBER(10), 
EMP_NAME VARCHAR2(50) NOT NULL,
DEP_ID CHAR(6) ,
CONSTRAINT EMPLOYEES_EMPNUM_PK PRIMARY KEY(EMP_NUMBER),  
CONSTRAINT EMPLOYEES_ DEP_ID _FK FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT);


INSERT INTO EMPLOYEES VALUES (1001, 'ASTOLFO', 'CS100');
INSERT INTO EMPLOYEES VALUES (1002, 'YAMAN', 'CS100');


INSERT INTO DEPARTMENT VALUES ('CS100', 'COMP. SC.', 'D');
INSERT INTO DEPARTMENT VALUES ('HR100', 'HR', 'A');
INSERT INTO DEPARTMENT VALUES ('ACC100', 'ACCOUNTING', NULL);

SELECT * FROM DEPARTMENT


DELETE DEPARTMENT
WHERE DEPT_NUMBER = 'CS100'

ALTER TABLE EMPLOYEES
DROP CONSTRAINT EMPLOYEES_DEP_ID_FK;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_DEP_ID_FK FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT ON DELETE SET NULL;

ROLLBACK

UPDATE EMPLOYEES
SET DEP_ID = 'HR100';

ALTER TABLE EMPLOYEES
DROP CONSTRAINT EMPLOYEES_DEP_ID_FK;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_DEP_ID_FK FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT ON DELETE CASCADE;