-- AUTHOER @Candl3_

SELECT * FROM BRANCH;
SELECT * FROM STAFF;
SELECT * FROM PROPERTYFORRENT;
SELECT * FROM CLIENT;
SELECT * FROM PRIVATEOWNER;
SELECT * FROM VIEWING;
SELECT * FROM REGISTRATION;


-- FORMAT TYPE
--  SELECT [DISTINCT]
-- { *| {COLUMNS | COLUMEXPRESSION { AS NEWNAME}] [,..]}
-- FROM     TABLENAME [ALIAS] [,...]


-- LIST FIRST AND LAST NAMES OF ALL STAFF 

SELECT FNAME, LNAME
FROM STAFF;

-- LIST ALL STAFF INFORMATION

-- SELECT * (A WAY TO SELECT EVERYTHING)
-- FROM STAFF

SELECT STAFFNO, FNAME, LNAME, POSITION, SEX, DOB, SALARY, BRANCHNO
FROM STAFF;
-- LIST ALL THE PROPERTIES

SELECT *
FROM PROPERTYFORRENT;

-- LIST STREET AND NUMBER OF ROOMS IN EACH PROPERTY

SELECT STREET, ROOM
FROM PROPERTYFORRENT;

SELECT *
FROM STAFF
-- ORDER BY FNAME DESC;
WHERE SALARY > 20000


-- LIST THE SALARY AFTER ADDIN 10%

-- TO ADD NEW NAME TO A COLUMN WE SHOULD ADD [AS] BEFORE THE NEW NAME
-- IF YOUR NEW NAME HAS SPACES, USE "" FOR THE NEW NAME

SELECT SALARY, SALARY * 1.1 AS NEW_SALARY, FNAME AS "FIRST NAME"
FROM STAFF;

SELECT BRANCH.*, STAFF.
-- SELECT B.*, S.* ( IS ALSO DO-ABLE TO SELECT EVERYTHING) 
FROM STAFF, BRANCH;


SELECT DISTINCT PROPERTYNO
FROM VIEWING;


-- TEST 

SELECT DISTINCT CITY FROM BRANCH
WHERE CITY = 'London' OR CITY = 'Glasgow';
-- TO AVOID THE CASE SENSITIVITY
-- WHERE UPPER(CITY) = 'LONDON' OR CITY = 'GLASGOW';


SELECT * 
-- AUTHOR @Candl3_

FROM STAFF
WHERE SALARY BETWEEN 20000 AND 30000;
-- THE ABOVE STATEMENT CAN BE REWRITTEN AS
-- WHERE SALARY >= 20000 AND SALARY =< 30000



SELECT *
FROM STAFF
--  USING A % SIGN BEFORE/AFTER THE LETTER TELLS THE PROGRAM WHERE TO IGNORE
-- FOR EXAMPLE USING %A TELLS THE PROGRAM IGNORE ANYTHING BEFORE THE LETTER A, THE ... MUST END WITH A
WHERE FNAME LIKE '%a%'
WHERE FNAME LIKE 'J%'
WHERE FNAME LIKE '%n';


SELECT * 
FROM PRIVATEOWNER
WHERE FNAME LIKE 'j_'
WHERE ADDRESS LIKE '%St%';


SELECT *
FROM VIEWING
WHERE VCOMMENT IS NOT NULL

SELECT PROPERTYNO, TYPE, RENT
FROM PROPERTYFORRENT
--  THIS IS ASCENDING
-- ORDER BY TYPE;
-- THIS IS DESCENDING
-- ORDER BY TYPE DESCENDING;
ORDER BY TYPE, RENT DESC;

