 -- author @Candl3_

SELECT TABLE_NAME FROM USER_TABLES;

SELECT * FROM  STAFF WHERE SALARY > 10000;

SELECT STAFFNO, FNAME, LNAME
FROM STAFF;
SELECT * FROM BRANCH;


SELECT * FROM STAFF
WHERE SALARY BETWEEN 20000 AND 30000
ORDER BY FNAME DESC;

SELECT *
FROM STAFF
WHERE FNAME LIKE 'A%'; -- THE VALUES INSIDE THE QUOTATION IS CAASE SENSITIVE

SELECT MAX(SALARY), MIN(SALARY), COUNT(SALARY), AVG(SALARY), SUM(SALARY)
FROM STAFF;

SELECT COUNT(VCOMMENT), COUNT(*)
FROM VIEWING;

SELECT MAX(FNAME), MIN(FNAME)
FROM STAFF;

-- YOU CANT USE AN AGGREGATE FUNCTION WITH ANOTHER FUNCTION
-- AGGREGATE IS ( MIN, MAX, COUNT(), COUNT(*), AVG, SUM)
-- IF A TABLE RETURNS VALUES OF RATIOS 1:M IT'S NOT POSSIBLE TO USE

SELECT COUNT(PROPERTYNO) AS "NUMBER OF PROPERTIES"
FROM PROPERTYFORRENT
WHERE RENT > 350;

SELECT COUNT(PROPERTYNO) AS "NUMBER OF VIEWED PROPERTY"
FROM VIEWING
WHERE TO_CHAR (VIEWDATE, 'MM') = 05 AND TO_CHAR(VIEWDATE, 'YYYY') = 2015
WHERE VIEWDATE BETWEEN '01-MAY-2015' AND '31-MAY-2015'

SELECT COUNT(STAFFNO) AS "NUMBER OF MANAGERS", SUM(SALARY) AS "SALARY SUM"
FROM STAFF
WHERE UPPER(POSITION) = 'MANAGER'

-- FINDING THE NUMBER OF STAFF IN EACH BRANCH ( USING GROUP BY) DISPLAY ONLY BRANCHES WITH MORE THAN 2 STAFF

SELECT BRANCHNO, COUNT(STAFFNO)
FROM STAFF
GROUP BY BRANCHNO
HAVING COUNT(STAFFNO) > 2;

-- WHERE FILTERS AN ENTIRE TABLE
-- HAVING FILTERS BY GROUP


-- LIST ALL CITIES WHERE THERE IS EITHER A BRANCHNO OR A PROPERTY

SELECT CITY, BRANCHNO FROM BRANCH
UNION
SELECT CITY, BRANCHNO FROM PROPERTYFORRENT

SELECT CITY FROM BRANCH
INTERSECT
SELECT CITY FROM PROPERTYFORRENT

SELECT CITY FROM BRANCH
MINUS
SELECT CITY FROM PROPERTYFORRENT

SELECT * FROM BRANCH, STAFF
WHERE STAFF.BRANCHNO = BRANCH.BRANCHNO
