SELECT TABLE_NAME FROM USER_TABLES

-- LIST THE STAFF FNAME, LNAME & CITY OF THE BRANCH  WHERE THEY ARE WORKING IN

SELECT * FROM BRANCH
SELECT * FROM STAFF

SELECT FNAME, LNAME, CITY
FROM STAFF JOIN BRANCH
ON STAFF.BRANCHNO = BRANCH.BRANCHNO

-- OLD STYLE JOIN IS

-- SELECT FNAME, LNAME, CITY, S.BRANCHNO, ROOMS, TYPE
-- FROM STAFF S, BRANCH B, PROPERTYFORRENT P
-- WHERE S.BRANCHNO = B.BRANCHNO
-- AND S.STAFFNO = P.STAFFNO


-- LIST THE NAMES OF ALL CLIENTS WHO HAVE VIEWED A PROPERTY ALONG WITH ANY COMMENT SUPPLIED

SELECT * FROM CLIENT
SELECT * FROM VIEWING

SELECT C.*, V.*
FROM CLIENT C JOIN VIEWING V
ON C.CLIENTNO = V.CLIENTNO

SELECT * FROM CLIENT;
SELECT * FROM VIEWING;

--C.,V. FROM CLIENT C, VIEWING V
SELECT FNAME,LNAME, VCOMMENT
FROM CLIENT JOIN VIEWING 
ON CLIENT.CLIENTNO = VIEWING.CLIENTNO

SELECT * 
FROM CLIENT NATURAL JOIN VIEWING


-- LIST NUMBERS AND NAMES OF STAFF WHO MANAGES PROPERTY, AND THE PROPERTIES THEY MANAGE

SELECT * FROM STAFF
SELECT * FROM PROPERTYFORRENT


SELECT FNAME, LNAME, PROPERTYNO, TYPE
FROM STAFF S JOIN PROPERTYFORRENT P
ON S.STAFFNO = P.STAFFNO


-- LIST THE NAMES OF ALL CLIENTS WHO HAVE VIEWED A PROPERTY ALONG WITH ANY COMMENT SUPPLIED AND INCLUDE THE NUMBERS OF THE ROOMS

SELECT * FROM CLIENTS
SELECT * FROM VIEWING
SELECT * FROM PRROPERTYFORRENT

SELECT FNAME, LNAME, V.PROPERTYNO, VCOMMENT, ROOMS
FROM CLIENT C JOIN VIEWING V
ON C.CLIENTNO = V.CLIENTNO
JOIN PROPERTYFORRENT P
ON V.PROPERTYNO = P.PROPERTYNO

-- SELECT FNAME, LNAME, PROPERTYNO, VCOMMENT, ROOMS
-- FROM CLIENT NATURAL JOIN VIEWING NATURAL JOIN  PROPERTYFORRENT


-- USING OUTER JOIN

SELECT V*, V* 
FROM CLIENT C LEFT JOIN VIEWING V
ON C.CLIENTNO = V.CLIENTNO

SELECT * FROM STAFF;
SELECT * FROM PROPERTYFORRENT;

SELECT S., P.
FROM STAFF S LEFT JOIN PROPERTYFORRENT P
ON S.STAFFNO = P.STAFFNO

SELECT S., P.
FROM STAFF S RIGHT JOIN PROPERTYFORRENT P
ON S.STAFFNO = P.STAFFNO

SELECT S., P.
FROM STAFF S FULL JOIN PROPERTYFORRENT P
ON S.STAFFNO = P.STAFFNO


------------------------------------------------------------

SELECT * FROM STAFF

SELECT * FROM STAFF 
WHERE SEX  = 'F' AND SALARY > 10000

