CREATE OR REPLACE FUNCTION FUN_GET_PRICE ( VP_CODE PRODUCT.P_CODE%TYPE)
RETURN NUMBER
AS
VP_PRICE PRODUCT.P_PRICE%TYPE;
BEGIN
SELECT P_PRICE INTO VP_PRICE
FROM PRODUCT
WHERE P_CODE = VP_CODE;

RETURN VP_PRICE;
END;

SELECT P_CODE, FUN_GET_PRICE('11QER/31')
FROM PRODUCT
WHERE P_CODE = '11QER/31';


SELECT * 
FROM PRODUCT
WHERE FUN_GET_PRICE(P_CODE) > 100;



CREATE OR REPLACE FUNCTION TAX (VALUE NUMBER)
RETURN NUMBER IS
BEGIN
RETURN (VALUE * 08);
END TAX


CREATE OR REPLACE PROCEDURE PRC_INV_AMOUNTS (INV_NO NUMERIC)
AS
VSUBTOTAL NUMERIC;
VTAX NUMERIC;
VTOTAL NUMERIC;

BEGIN
SELECT SUM(LINE_TOTAL) INTO VSUBTOTAL
FROM LINE
WHERE INV_NUMBER = INV_NO;
VTAX := VSUBTOTAL * 0.08;
VTOTAL := VSUBTOTAL + VTAX;
UPDATE INVOICE
SET INV_SUBTOTAL = VSUBTOTAL, INV_TAX = V_TAX, INV_TOTAL = V_TOTAL
WHERE INV_NUMBER = INV_NO;
DBMS_OUTPUT.PUT_LINE('INVOICE HAS BEEN UPDATED!');
END;




