-- CREATING A TABLE
-- IN BRACKETS INDICATE THE NUMBER OF CHARACTERS FOR EACH ATTRIBUTE

CREATE TABLE DEPARTMENT
( DNO CHAR(5) PRIMARY KEY, -- WE INDICATED THIS AS THE PK 
DNAME VARCHAR(30),
DLOCATION VARCHAR(15));

-- IF WE WANT A PRIMARY KEY BETWEEN 2 ATTRIBUTES (FOR EXAMPLE, DNAME + DNOM)
-- PRIMARY KEY(DNO,DNAME));

SELECT * FROM DEPARTMENT;

-- INSERTING INFO INTO THE TABLE
-- INSERT INTO TABLE AND IN BRACKETS FILL ALL VARIABLES IN ORDER

INSERT INTO DEPARTMENT VALUES ('D1', 'COMP, SC.', 'D-BULD');
INSERT INTO DEPARTMENT VALUES ('D2', 'COMP, SC.', 'D-BULD');


-- TO DELETE A TABLE, USE THE FOLLOWING COMMAND
-- DROP TABLE DEPARTMENT





CREATE TABLE EMPLOYEE
( EMP_NO CHAR(9) PRIMARY KEY,
EMP_NAME VARCHAR(40),
DOB DATE,
DNO CHAR(5),
CONSTRAINT EMP_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENT); -- HOW TO USE A FOREIGN KEY

INSERT INTO EMPLOYEE VALUES('101', 'SMITH', NULL, 'D1');
INSERT INTO EMPLOYEE VALUES('102', 'ALEX', NULL, 'D1');
INSERT INTO EMPLOYEE VALUES('102', 'ALEX', NULL, 'D1');


