

CREATE OR REPLACE PROCEDURE MY_PROCEDURE
AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello, World!');
END;


-- HOW TO EXECUTE A PROCEDURE

EXEC MY_PROCEDURE

-- OR

BEGIN
MYPROCEDURE;
END;



CREATE OR REPLACE PROCEDURE MY_PROCEDURE (MSG IN VARCHAR)
AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello, World!' || MSG);
END;


EXEC MY_PROCEDURE (' DATABASE');

CREATE PROCEDURE CUSTCODE_BEGONE (CUSTID IN NUMBER)
AS
BEGIN
    DELETE FROM CUSTOMER 
    WHERE CUS_CODE = CUSTID;
END;

EXEC CUSTCODE_BEGONE (10019);

SELECT * FROM CUSTOMER


CREATE OR REPLACE PROCEDURE CUSTCODE_BEGONE (CUSTID IN NUMBER)
AS
 CHKID NUMBER;
BEGIN
    SELECT COUNT(*) INTO CHKID FROM CUSTOMER
    WHERE CUS_CODE = CUSTID;
    IF (CHKID > 0) THEN
        DELETE FROM CUSTOMER 
        WHERE CUS_CODE = CUSTID;
    ELSE
        DBMS_OUTPUT.PUT_LINE('Customer does not exist!');
    END IF;
END;


/* create a procedure to assign an additional 5 percent discount for products
when the quantity on hand is ore than or equal to twice the minimum quantity*/

CREATE OR REPLACE PROCEDURE PROC_P_DISCOUNT (PER NUMERIC)
AS
BEGIN
    UPDATE PRODUCT;
    SET P_DISCOUNT = P_DISCOUT + PER
    WHERE P_QOH >= 2 * P_MIN;
    DBMS.OUTPUT.PUT_LINE(' PRODUCTS HAVE BEEN UPDATED ');
END;



