CREATE VIEW VW_STAFFOFB003
AS
SELECT S.*
FROM STAFF S JOIN BRANCH B
ON S.BRANCHNO = B.BRANCHNO
WHERE S.BRANCHNO = 'B0003';

SELECT * FROM VW_STAFFOFB003


CREATE OR REPLACE VIEW VW_STAFFOFB003 (EMPLOYEE_FNAME, EMPLOYEE_LNAME)
AS
SELECT S.FNAME, S.LNAME
FROM STAFF S JOIN BRANCH B
ON S.BRANCHNO = B.BRANCHNO
WHERE S.BRANCHNO = 'B0003';

CREATE OR REPLACE VIEW VW_STAFFOFB003
AS
SELECT COUNT(*) AS NUMBORE_OF_EMPLOYEES
FROM STAFF S JOIN BRANCH B
ON S.BRANCHNO = B.BRANCHNO
WHERE S.BRANCHNO = 'B0003'
WITH CHECK OPTION;

INSERT INTO VW_STAFFOFB0003 VALUES ('C100', 'AAAAAA', 'BBBBBB', 'B005');
